<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Gesamtzaehler" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
				<Attribute Name="YPOSITION" Type="STRING" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="CU" Type="Event" Comment="Count Up">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</SubAppEvent>
			<SubAppEvent Name="CD" Type="Event" Comment="Count Down">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</SubAppEvent>
			<SubAppEvent Name="R" Type="Event" Comment="Reset">
				<Attribute Name="YPOSITION" Type="STRING" Value="184"/>
			</SubAppEvent>
			<SubAppEvent Name="rVT" Type="Event" Comment="refresh VT">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF" Type="Event" Comment="Confirmation -- Counter Value was changed">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="CV" Type="UDINT" Comment="Counter Value"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_CTUD_UDINT_Gesamtzaehler" Type="E_CTUD_UDINT" Comment="" x="400.0" y="400.0">
		</FB>
		<FB Name="Q_NumericValue_Gesamtzaehler" Type="Q_NumericValue" Comment="" x="2933.3333333333335" y="933.3333333333334">
			<Parameter Name="u16ObjId" Value="21001"/>
		</FB>
		<FB Name="NVS_UDINT_Gesamtzaehler" Type="NVS_UDINT" Comment="" x="2933.3333333333335" y="2266.666666666667">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="'Gesamtzaehler'"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_NumericValue_Gesamtzaehler.INIT" Comment="" dx1="4213.333333333334"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.CO" Destination="Q_NumericValue_Gesamtzaehler.REQ" Comment="" dx1="80.0"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.RO" Destination="Q_NumericValue_Gesamtzaehler.REQ" Comment="" dx1="80.0"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.LDO" Destination="Q_NumericValue_Gesamtzaehler.REQ" Comment="" dx1="80.0"/>
			<Connection Source="CU" Destination="E_CTUD_UDINT_Gesamtzaehler.CU" Comment="" dx1="886.6666666666667"/>
			<Connection Source="CD" Destination="E_CTUD_UDINT_Gesamtzaehler.CD" Comment="" dx1="780.0"/>
			<Connection Source="R" Destination="E_CTUD_UDINT_Gesamtzaehler.R" Comment="" dx1="793.3333333333334"/>
			<Connection Source="INIT" Destination="NVS_UDINT_Gesamtzaehler.INIT" Comment="" dx1="4226.666666666667"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.CO" Destination="NVS_UDINT_Gesamtzaehler.SET" Comment="" dx1="406.6666666666667"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.RO" Destination="NVS_UDINT_Gesamtzaehler.SET" Comment="" dx1="300.0"/>
			<Connection Source="NVS_UDINT_Gesamtzaehler.GETO" Destination="E_CTUD_UDINT_Gesamtzaehler.LD" Comment="" dx1="406.6666666666667" dx2="240.0" dy="-560.0"/>
			<Connection Source="NVS_UDINT_Gesamtzaehler.INITO" Destination="NVS_UDINT_Gesamtzaehler.GET" Comment="" dx1="273.33333333333337" dx2="453.33333333333337" dy="-193.33333333333334"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.CO" Destination="CNF" Comment="" dx1="2606.666666666667"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.RO" Destination="CNF" Comment="" dx1="2606.666666666667"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.LDO" Destination="CNF" Comment="" dx1="2606.666666666667"/>
			<Connection Source="rVT" Destination="Q_NumericValue_Gesamtzaehler.REQ" Comment="" dx1="3666.666666666667"/>
			<Connection Source="rVT" Destination="CNF" Comment="" dx1="7600.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.CV" Destination="Q_NumericValue_Gesamtzaehler.u32NewValue" Comment="" dx1="620.0"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.CV" Destination="NVS_UDINT_Gesamtzaehler.VALUE" Comment="" dx1="193.33333333333334"/>
			<Connection Source="NVS_UDINT_Gesamtzaehler.VALUEO" Destination="E_CTUD_UDINT_Gesamtzaehler.PV" Comment="" dx1="640.0" dx2="133.33333333333334" dy="-1086.6666666666667"/>
			<Connection Source="E_CTUD_UDINT_Gesamtzaehler.CV" Destination="CV" Comment="" dx1="173.33333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
