<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GesamtzaehlerVergleich" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-18">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="CV" Type="UDINT" Comment="Counter Value"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue_Gesamtzaehler_Ziel_erreicht" Type="Q_NumericValue" Comment="" x="6000.0" y="-933.3333333333334">
			<Parameter Name="u16ObjId" Value="27003"/>
		</FB>
		<FB Name="F_GE" Type="F_GE" Comment="" x="2666.666666666667" y="-666.6666666666667">
			<Parameter Name="IN2" Value="UDINT#5"/>
		</FB>
		<FB Name="F_SEL" Type="F_SEL" Comment="" x="4533.333333333334" y="-533.3333333333334">
			<Parameter Name="IN0" Value="UDINT#16#FFFF"/>
			<Parameter Name="IN1" Value="UDINT#11012"/>
		</FB>
		<FB Name="NVS_UDINT" Type="NVS_UDINT" Comment="" x="4266.666666666667" y="800.0">
		</FB>
		<FB Name="IUDINT" Type="IUDINT" Comment="" x="2400.0" y="933.3333333333334">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_NumericValue_Gesamtzaehler_Ziel_erreicht.INIT" Comment="" dx1="1733.3333333333335"/>
			<Connection Source="REQ" Destination="F_GE.REQ" Comment="" dx1="666.6666666666667"/>
			<Connection Source="F_GE.CNF" Destination="F_SEL.REQ" Comment="" dx1="700.0"/>
			<Connection Source="F_SEL.CNF" Destination="Q_NumericValue_Gesamtzaehler_Ziel_erreicht.REQ" Comment="" dx1="386.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CV" Destination="F_GE.IN1" Comment="" dx1="340.0"/>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue_Gesamtzaehler_Ziel_erreicht.u32NewValue" Comment="" dx1="673.3333333333334"/>
			<Connection Source="F_GE.OUT" Destination="F_SEL.G" Comment="" dx1="700.0"/>
			<Connection Source="IUDINT.IN" Destination="NVS_UDINT.VALUE" Comment="" dx1="686.6666666666667"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
