<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GesamtzaehlerVergleich" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-18">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
			<SubAppEvent Name="rVT" Type="Event" Comment="refresh VT">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="CV" Type="UDINT" Comment="Counter Value"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue_Gesamtzaehler_Ziel_erreicht" Type="Q_NumericValue" Comment="" x="6000.0" y="-929.4117647058823">
			<Parameter Name="u16ObjId" Value="27003"/>
		</FB>
		<FB Name="F_GE" Type="F_GE" Comment="" x="2664.705882352941" y="-664.7058823529411">
		</FB>
		<FB Name="F_SEL" Type="F_SEL" Comment="" x="4529.411764705882" y="-529.4117647058823">
			<Parameter Name="IN0" Value="UDINT#16#FFFF"/>
			<Parameter Name="IN1" Value="UDINT#11012"/>
		</FB>
		<FB Name="NVS_UDINT_Gesamtziel" Type="NVS_UDINT" Comment="" x="4258.823529411764" y="799.9999999999999">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="'Gesamtziel'"/>
		</FB>
		<FB Name="NumberVariable_Gesamtziel" Type="IUDINT" Comment="" x="2352.9411764705883" y="1058.8235294117646">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_Gesamtziel" Type="Q_NumericValue" Comment="" x="8117.647058823529" y="941.1764705882352">
			<Parameter Name="u16ObjId" Value="21002"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_NumericValue_Gesamtzaehler_Ziel_erreicht.INIT" Comment="" dx1="1729.4117647058822"/>
			<Connection Source="REQ" Destination="F_GE.REQ" Comment="" dx1="664.7058823529411"/>
			<Connection Source="F_GE.CNF" Destination="F_SEL.REQ" Comment="" dx1="700.0"/>
			<Connection Source="F_SEL.CNF" Destination="Q_NumericValue_Gesamtzaehler_Ziel_erreicht.REQ" Comment="" dx1="382.35294117647055"/>
			<Connection Source="INIT" Destination="NumberVariable_Gesamtziel.INIT" Comment="" dx1="117.6470588235294"/>
			<Connection Source="INIT" Destination="NVS_UDINT_Gesamtziel.INIT" Comment="" dx1="117.6470588235294"/>
			<Connection Source="NumberVariable_Gesamtziel.IND" Destination="NVS_UDINT_Gesamtziel.SET" Comment="" dx1="594.1176470588235"/>
			<Connection Source="NVS_UDINT_Gesamtziel.INITO" Destination="NVS_UDINT_Gesamtziel.GET" Comment="" dx1="300.0" dx2="305.88235294117646" dy="-300.0"/>
			<Connection Source="NVS_UDINT_Gesamtziel.GETO" Destination="Q_NumericValue_Gesamtziel.REQ" Comment="" dx1="764.7058823529411"/>
			<Connection Source="INIT" Destination="Q_NumericValue_Gesamtziel.INIT" Comment="" dx1="6888.235294117647"/>
			<Connection Source="NVS_UDINT_Gesamtziel.GETO" Destination="F_GE.REQ" Comment="" dx1="464.70588235294116" dx2="252.9411764705882" dy="-752.9411764705882"/>
			<Connection Source="NVS_UDINT_Gesamtziel.SETO" Destination="F_GE.REQ" Comment="" dx1="376.4705882352941" dx2="364.70588235294116" dy="-529.4117647058823"/>
			<Connection Source="rVT" Destination="Q_NumericValue_Gesamtziel.REQ" Comment="" dx1="6880.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CV" Destination="F_GE.IN1" Comment="" dx1="335.2941176470588"/>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue_Gesamtzaehler_Ziel_erreicht.u32NewValue" Comment="" dx1="670.5882352941176"/>
			<Connection Source="F_GE.OUT" Destination="F_SEL.G" Comment="" dx1="700.0"/>
			<Connection Source="NumberVariable_Gesamtziel.IN" Destination="NVS_UDINT_Gesamtziel.VALUE" Comment="" dx1="676.470588235294"/>
			<Connection Source="NVS_UDINT_Gesamtziel.VALUEO" Destination="Q_NumericValue_Gesamtziel.u32NewValue" Comment="" dx1="764.7058823529411"/>
			<Connection Source="NVS_UDINT_Gesamtziel.VALUEO" Destination="F_GE.IN2" Comment="" dx1="576.470588235294" dx2="135.2941176470588" dy="-1288.235294117647"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
