<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GesamtzaehlerVergleich" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-18">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
			<SubAppEvent Name="rVT" Type="Event" Comment="refresh VT">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="CV" Type="UDINT" Comment="Counter Value"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue_Gesamtzaehler_Ziel_erreicht" Type="Q_NumericValue" Comment="" x="6400.0" y="-933.3333333333334">
			<Parameter Name="u16ObjId" Value="ObjectPointer_Gesamtziel"/>
		</FB>
		<FB Name="F_GE" Type="F_GE" Comment="" x="2660.0" y="-660.0">
		</FB>
		<FB Name="NVS_UDINT_Gesamtziel" Type="NVS_UDINT" Comment="" x="4253.333333333334" y="793.3333333333334">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="KEY_GESAMTZIEL"/>
		</FB>
		<FB Name="NumberVariable_Gesamtziel" Type="IUDINT" Comment="" x="2346.666666666667" y="1053.3333333333335">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_Gesamtziel" Type="Q_NumericValue" Comment="" x="9066.666666666668" y="933.3333333333334">
			<Parameter Name="u16ObjId" Value="NumberVariable_Gesamtziel"/>
		</FB>
		<FB Name="F_SEL" Type="F_SEL" Comment="" x="4526.666666666667" y="-526.6666666666667">
			<Parameter Name="IN0" Value="ID_NULL"/>
			<Parameter Name="IN1" Value="OutputString_ZielErreicht"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_NumericValue_Gesamtzaehler_Ziel_erreicht.INIT" Comment="" dx1="4466.666666666667"/>
			<Connection Source="REQ" Destination="F_GE.REQ" Comment="" dx1="660.0"/>
			<Connection Source="INIT" Destination="NumberVariable_Gesamtziel.INIT" Comment="" dx1="113.33333333333334"/>
			<Connection Source="INIT" Destination="NVS_UDINT_Gesamtziel.INIT" Comment="" dx1="113.33333333333334"/>
			<Connection Source="NumberVariable_Gesamtziel.IND" Destination="NVS_UDINT_Gesamtziel.SET" Comment="" dx1="593.3333333333334"/>
			<Connection Source="NVS_UDINT_Gesamtziel.INITO" Destination="NVS_UDINT_Gesamtziel.GET" Comment="" dx1="300.0" dx2="300.0" dy="-300.0"/>
			<Connection Source="NVS_UDINT_Gesamtziel.GETO" Destination="Q_NumericValue_Gesamtziel.REQ" Comment="" dx1="760.0"/>
			<Connection Source="INIT" Destination="Q_NumericValue_Gesamtziel.INIT" Comment="" dx1="7520.0"/>
			<Connection Source="NVS_UDINT_Gesamtziel.GETO" Destination="F_GE.REQ" Comment="" dx1="460.0" dx2="246.66666666666669" dy="-746.6666666666667"/>
			<Connection Source="NVS_UDINT_Gesamtziel.SETO" Destination="F_GE.REQ" Comment="" dx1="373.33333333333337" dx2="360.0" dy="-526.6666666666667"/>
			<Connection Source="rVT" Destination="Q_NumericValue_Gesamtziel.REQ" Comment="" dx1="7353.333333333334"/>
			<Connection Source="F_GE.CNF" Destination="F_SEL.REQ" Comment="" dx1="700.0" dx2="700.0" dy="0.0"/>
			<Connection Source="F_SEL.CNF" Destination="Q_NumericValue_Gesamtzaehler_Ziel_erreicht.REQ" Comment="" dx1="286.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CV" Destination="F_GE.IN1" Comment="" dx1="333.33333333333337"/>
			<Connection Source="NumberVariable_Gesamtziel.IN" Destination="NVS_UDINT_Gesamtziel.VALUE" Comment="" dx1="673.3333333333334"/>
			<Connection Source="NVS_UDINT_Gesamtziel.VALUEO" Destination="Q_NumericValue_Gesamtziel.u32NewValue" Comment="" dx1="760.0"/>
			<Connection Source="NVS_UDINT_Gesamtziel.VALUEO" Destination="F_GE.IN2" Comment="" dx1="573.3333333333334" dx2="133.33333333333334" dy="-1286.6666666666667"/>
			<Connection Source="F_GE.OUT" Destination="F_SEL.G" Comment="" dx1="700.0" dx2="700.0" dy="0.0"/>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue_Gesamtzaehler_Ziel_erreicht.u32NewValue" Comment="" dx1="760.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
