<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Gesamtzaehler" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Button_PlusPlus" Type="IE" Comment="" x="133.33333333333334" y="-533.3333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Button_PlusPlus.INIT" Comment="" dx1="773.3333333333334"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
