<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Softkeys" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_SoftkeyMapping_UP" Comment="" x="1066.6666666666667" y="933.3333333333334">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="5000"/>
			<Parameter Name="DigitalInput_1" Value="&quot;SoftKey_PlusPlus&quot;"/>
			<Parameter Name="u16ObjId_2" Value="5001"/>
			<Parameter Name="DigitalInput_2" Value="&quot;SoftKey_Reset_Gesamtzaehler&quot;"/>
			<Parameter Name="u16ObjId_3" Value="5002"/>
			<Parameter Name="DigitalInput_3" Value="&quot;SoftKey_Reset_Tageszaehler&quot;"/>
			<Parameter Name="u16ObjId_4" Value="5003"/>
			<Parameter Name="DigitalInput_4" Value="&quot;SoftKey_MinusMinus&quot;"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping_UP.INIT" Comment="" dx1="80.0"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
