<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_NumericValue" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_NumericValueInputMapping" Comment="" x="1058.8235294117646" y="929.4117647058823">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="21002"/>
			<Parameter Name="NumericValueInput_1" Value="&quot;NumberVariable_Gesamtziel&quot;"/>
			<Parameter Name="u16ObjId_2" Value="21003"/>
			<Parameter Name="NumericValueInput_2" Value="&quot;NumberVariable_Tagesziel&quot;"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping_UP.INIT" Comment="" dx1="76.47058823529412" dx2="76.47058823529412" dy="0.0"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
