<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_NumericValue" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_NumericValueInputMapping" Comment="" x="1053.3333333333335" y="926.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="255" Comment=""/>
			<Parameter Name="u16ObjId_1" Value="NumberVariable_Gesamtziel" Comment=""/>
			<Parameter Name="NumericValueInput_1" Value="'Counter.GesamtzaehlerVergleich.IN_NumberVariable_Gesamtziel'" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="NumberVariable_Tagesziel" Comment=""/>
			<Parameter Name="NumericValueInput_2" Value="'Counter.TageszaehlerVergleich.IN_NumberVariable_Tagesziel'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping_UP.INIT" Comment="" dx1="73.33333333333334" dx2="73.33333333333334" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
