<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Softkeys" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_SoftkeyMapping_UP" Comment="" x="1066.6666666666667" y="933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="255" Comment=""/>
			<Parameter Name="u16ObjId_1" Value="SoftKey_PlusPlus" Comment=""/>
			<Parameter Name="DigitalInput_1" Value="'Counter.PlusPlus.SoftKey_PlusPlus'" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="SoftKey_Reset_Gesamtzaehler" Comment=""/>
			<Parameter Name="DigitalInput_2" Value="'Counter.Reset_Gesamtzaehler.SoftKey_Reset_Gesamtzaehler'" Comment=""/>
			<Parameter Name="u16ObjId_3" Value="SoftKey_Reset_Tageszaehler" Comment=""/>
			<Parameter Name="DigitalInput_3" Value="'Counter.Reset_Tageszaehler.SoftKey_Reset_Tageszaehler'" Comment=""/>
			<Parameter Name="u16ObjId_4" Value="SoftKey_MinusMinus" Comment=""/>
			<Parameter Name="DigitalInput_4" Value="'Counter.MinusMinus.SoftKey_MinusMinus'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping_UP.INIT" Comment="" dx1="80.0"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
