<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Buttons" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_ButtonMapping_UP" Type="UT_ButtonMapping_UP" Comment="" x="900.0" y="900.0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="Button_PlusPlus"/>
			<Parameter Name="DigitalInput_1" Value="'Button_PlusPlus'"/>
			<Parameter Name="u16ObjId_2" Value="Button_Reset_Gesamtzaehler"/>
			<Parameter Name="DigitalInput_2" Value="'Button_Reset_Gesamtzaehler'"/>
			<Parameter Name="u16ObjId_3" Value="Button_Reset_Tageszaehler"/>
			<Parameter Name="DigitalInput_3" Value="'Button_Reset_Tageszaehler'"/>
			<Parameter Name="u16ObjId_4" Value="Button_MinusMinus"/>
			<Parameter Name="DigitalInput_4" Value="'Button_MinusMinus'"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_ButtonMapping_UP.INIT" Comment="" dx1="520.0" dx2="520.0" dy="0.0"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
