<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-19">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="mapping_NumericValue" Type="mapping_NumericValue" Comment="" x="0.0" y="0.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="mapping_Softkeys" Type="mapping_Softkeys" Comment="" x="0.0" y="800.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="mapping_Buttons" Type="mapping_Buttons" Comment="" x="0.0" y="400.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="mapping_aux" Type="mapping_aux" Comment="" x="0.0" y="1200.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="mapping_NumericValue.INIT" Comment=""/>
			<Connection Source="INIT" Destination="mapping_Softkeys.INIT" Comment=""/>
			<Connection Source="INIT" Destination="mapping_Buttons.INIT" Comment=""/>
			<Connection Source="INIT" Destination="mapping_aux.INIT" Comment=""/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
