<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="MinusMinus" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Button_MinusMinus" Type="IE" Comment="" x="0.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_MinusMinus" Type="IE" Comment="" x="0.0" y="933.3333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AuxFunction2_MinusMinus" Type="IX" Comment="" x="133.33333333333334" y="1866.6666666666667">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SWITCH_MinusMinus" Type="E_SWITCH" Comment="" x="1466.6666666666667" y="2000.0">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Button_MinusMinus.INIT" Comment="" dx1="693.3333333333334"/>
			<Connection Source="Button_MinusMinus.IND" Destination="IND" Comment="" dx1="1566.6666666666667"/>
			<Connection Source="INIT" Destination="SoftKey_MinusMinus.INIT" Comment="" dx1="586.6666666666667"/>
			<Connection Source="SoftKey_MinusMinus.IND" Destination="IND" Comment="" dx1="1626.6666666666667"/>
			<Connection Source="INIT" Destination="AuxFunction2_MinusMinus.INIT" Comment="" dx1="480.0"/>
			<Connection Source="AuxFunction2_MinusMinus.IND" Destination="E_SWITCH_MinusMinus.EI" Comment="" dx1="113.33333333333334"/>
			<Connection Source="E_SWITCH_MinusMinus.EO0" Destination="IND" Comment="" dx1="826.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AuxFunction2_MinusMinus.IN" Destination="E_SWITCH_MinusMinus.G" Comment="" dx1="320.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
