<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Reset_Gesamtzaehler" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Button_Reset_Gesamtzaehler" Type="IE" Comment="" x="0.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_Reset_Gesamtzaehler" Type="IE" Comment="" x="0.0" y="933.3333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Button_Reset_Gesamtzaehler.INIT" Comment="" dx1="693.3333333333334"/>
			<Connection Source="Button_Reset_Gesamtzaehler.IND" Destination="IND" Comment="" dx1="1566.6666666666667"/>
			<Connection Source="INIT" Destination="SoftKey_Reset_Gesamtzaehler.INIT" Comment="" dx1="586.6666666666667"/>
			<Connection Source="SoftKey_Reset_Gesamtzaehler.IND" Destination="IND" Comment="" dx1="1626.6666666666667"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
