<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Tageszaehler" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
				<Attribute Name="YPOSITION" Type="STRING" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="CU" Type="Event" Comment="Count Up">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</SubAppEvent>
			<SubAppEvent Name="CD" Type="Event" Comment="Count Down">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</SubAppEvent>
			<SubAppEvent Name="R" Type="Event" Comment="Reset">
				<Attribute Name="YPOSITION" Type="STRING" Value="184"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_CTUD_UDINT_Tageszaehler" Type="E_CTUD_UDINT" Comment="" x="400.0" y="400.0">
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="2533.3333333333335" y="933.3333333333334">
			<Parameter Name="u16ObjId" Value="21000"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_NumericValue.INIT" Comment="" dx1="3600.0"/>
			<Connection Source="E_CTUD_UDINT_Tageszaehler.CO" Destination="Q_NumericValue.REQ" Comment="" dx1="80.0"/>
			<Connection Source="E_CTUD_UDINT_Tageszaehler.RO" Destination="Q_NumericValue.REQ" Comment="" dx1="80.0"/>
			<Connection Source="E_CTUD_UDINT_Tageszaehler.LDO" Destination="Q_NumericValue.REQ" Comment="" dx1="80.0"/>
			<Connection Source="CU" Destination="E_CTUD_UDINT_Tageszaehler.CU" Comment="" dx1="1013.3333333333334"/>
			<Connection Source="CD" Destination="E_CTUD_UDINT_Tageszaehler.CD" Comment="" dx1="340.0"/>
			<Connection Source="R" Destination="E_CTUD_UDINT_Tageszaehler.R" Comment="" dx1="446.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTUD_UDINT_Tageszaehler.CV" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="280.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
