<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="TageszaehlerVergleich" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-18">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
			<SubAppEvent Name="rVT" Type="Event" Comment="refresh VT">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="CV" Type="UDINT" Comment="Counter Value"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue_Tageszaehler_Ziel_erreicht" Type="Q_NumericValue" Comment="" x="6400.0" y="-926.6666666666667">
			<Parameter Name="u16ObjId" Value="ObjectPointer_Tagesziel"/>
		</FB>
		<FB Name="F_GE" Type="F_GE" Comment="" x="2660.0" y="-660.0">
		</FB>
		<FB Name="NVS_UDINT_Tagesziel" Type="NVS_UDINT" Comment="" x="5060.0" y="800.0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="KEY_TAGESZIEL"/>
		</FB>
		<FB Name="Q_NumericValue_Tagesziel" Type="Q_NumericValue" Comment="" x="9200.0" y="926.6666666666667">
			<Parameter Name="u16ObjId" Value="NumberVariable_Tagesziel"/>
		</FB>
		<FB Name="F_SEL" Type="F_SEL" Comment="" x="4520.0" y="-520.0">
			<Parameter Name="IN0" Value="ID_NULL"/>
			<Parameter Name="IN1" Value="OutputString_ZielErreicht"/>
		</FB>
		<FB Name="IN_NumberVariable_Tagesziel" Type="ID" Comment="" x="1600.0" y="1200.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" Comment="" x="3060.0" y="1200.0">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_NumericValue_Tageszaehler_Ziel_erreicht.INIT" Comment="" dx1="4520.0"/>
			<Connection Source="REQ" Destination="F_GE.REQ" Comment="" dx1="660.0"/>
			<Connection Source="INIT" Destination="NVS_UDINT_Tagesziel.INIT" Comment="" dx1="80.0"/>
			<Connection Source="NVS_UDINT_Tagesziel.INITO" Destination="NVS_UDINT_Tagesziel.GET" Comment="" dx1="300.0" dx2="300.0" dy="-300.0"/>
			<Connection Source="NVS_UDINT_Tagesziel.GETO" Destination="Q_NumericValue_Tagesziel.REQ" Comment="" dx1="760.0"/>
			<Connection Source="INIT" Destination="Q_NumericValue_Tagesziel.INIT" Comment="" dx1="7700.0"/>
			<Connection Source="NVS_UDINT_Tagesziel.GETO" Destination="F_GE.REQ" Comment="" dx1="460.0" dx2="240.0" dy="-740.0"/>
			<Connection Source="NVS_UDINT_Tagesziel.SETO" Destination="F_GE.REQ" Comment="" dx1="360.0" dx2="360.0" dy="-520.0"/>
			<Connection Source="rVT" Destination="Q_NumericValue_Tagesziel.REQ" Comment="" dx1="7560.0"/>
			<Connection Source="F_GE.CNF" Destination="F_SEL.REQ" Comment="" dx1="700.0" dx2="700.0" dy="0.0"/>
			<Connection Source="F_SEL.CNF" Destination="Q_NumericValue_Tageszaehler_Ziel_erreicht.REQ" Comment="" dx1="340.0"/>
			<Connection Source="INIT" Destination="IN_NumberVariable_Tagesziel.INIT" Comment="" dx1="80.0"/>
			<Connection Source="IN_NumberVariable_Tagesziel.IND" Destination="F_DWORD_TO_UDINT.REQ" Comment="" dx1="220.0"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="NVS_UDINT_Tagesziel.SET" Comment="" dx1="480.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CV" Destination="F_GE.IN1" Comment="" dx1="333.33333333333337"/>
			<Connection Source="NVS_UDINT_Tagesziel.VALUEO" Destination="Q_NumericValue_Tagesziel.u32NewValue" Comment="" dx1="760.0"/>
			<Connection Source="NVS_UDINT_Tagesziel.VALUEO" Destination="F_GE.IN2" Comment="" dx1="566.6666666666667" dx2="126.66666666666667" dy="-1280.0"/>
			<Connection Source="F_GE.OUT" Destination="F_SEL.G" Comment="" dx1="700.0" dx2="700.0" dy="0.0"/>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue_Tageszaehler_Ziel_erreicht.u32NewValue" Comment="" dx1="820.0"/>
			<Connection Source="IN_NumberVariable_Tagesziel.IN" Destination="F_DWORD_TO_UDINT.IN" Comment="" dx1="220.0"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="NVS_UDINT_Tagesziel.VALUE" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
