<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="VT_active" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-19">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="INITO" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EO" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_R_TRIG" Type="E_R_TRIG" Comment="" x="2266.666666666667" y="133.33333333333334">
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" Comment="" x="0.0" y="-133.33333333333334">
		</FB>
		<EventConnections>
			<Connection Source="E_R_TRIG.EO" Destination="EO" Comment="" dx1="980.0"/>
			<Connection Source="CbVtStatus.IND" Destination="E_R_TRIG.EI" Comment="" dx1="1440.0"/>
			<Connection Source="CbVtStatus.INITO" Destination="INITO" Comment="" dx1="1613.3333333333335"/>
			<Connection Source="INIT" Destination="CbVtStatus.INIT" Comment="" dx1="666.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CbVtStatus.qWsActive" Destination="E_R_TRIG.QI" Comment="" dx1="1440.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
